# Generated by Django 2.2.4 on 2019-08-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCF',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Game')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('common.game',),
        ),
    ]
