# Generated by Django 2.2.4 on 2019-08-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_four', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.gamecf',),
        ),
        migrations.CreateModel(
            name='NegamaxPrunningTTTAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.baseai',),
        ),
        migrations.CreateModel(
            name='NegamaxTTTAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.baseai',),
        ),
        migrations.CreateModel(
            name='NegimaxABTablesAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.baseai',),
        ),
        migrations.CreateModel(
            name='PrincipalVariationSearchAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.baseai',),
        ),
        migrations.CreateModel(
            name='RandomCFAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.baseai',),
        ),
        migrations.CreateModel(
            name='MTDFAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.negimaxabtablesai',),
        ),
    ]
