# Generated by Rok Strah on 2019-08-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_four', '0004_auto_20190817_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTDFAI',
        ),
        migrations.DeleteModel(
            name='BNSAI',
        ),
        migrations.CreateModel(
            name='BNSAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.negamaxabtablesai',),
        ),
        migrations.CreateModel(
            name='MTDFAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('connect_four.negamaxabtablesai',),
        ),
    ]
