# Generated by Django 2.2.3 on 2019-07-10 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tic_tac_toe', '0007_game_game_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUTTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_i', models.IntegerField(default=0)),
                ('prev_j', models.IntegerField(default=0)),
                ('player', models.IntegerField(default=1)),
                ('g0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g0', to='tic_tac_toe.Game')),
                ('g1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g1', to='tic_tac_toe.Game')),
                ('g2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g2', to='tic_tac_toe.Game')),
                ('g3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g3', to='tic_tac_toe.Game')),
                ('g4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g4', to='tic_tac_toe.Game')),
                ('g5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g5', to='tic_tac_toe.Game')),
                ('g6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g6', to='tic_tac_toe.Game')),
                ('g7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g7', to='tic_tac_toe.Game')),
                ('g8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_g8', to='tic_tac_toe.Game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_game', to='tic_tac_toe.Game')),
                ('p1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uttt_p1', to='tic_tac_toe.Player')),
                ('p2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uttt_p2', to='tic_tac_toe.Player')),
            ],
        ),
    ]
