# Generated by Django 2.2.3 on 2019-07-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ultimate_tic_tac_toe', '0003_gameuttt_childgame'), ('ultimate_tic_tac_toe', '0004_auto_20190712_2014')]

    dependencies = [
        ('tic_tac_toe', '0010_datacell'),
        ('ultimate_tic_tac_toe', '0002_gamettt_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUTTT_ChildGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_child_game', to='tic_tac_toe.GameTTT')),
                ('id_parent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ultimate_tic_tac_toe.GameUTTT')),
            ],
        ),
    ]
