# Generated by Django 2.2.3 on 2019-07-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_tic_tac_toe', '0003_gameuttt_childgame_squashed_0004_auto_20190712_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuttt',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uttt_game', to='tic_tac_toe.GameTTT'),
        ),
        migrations.AlterField(
            model_name='gameuttt_childgame',
            name='id_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_tic_tac_toe.GameUTTT'),
        ),
    ]
