# Generated by Django 2.2.3 on 2019-07-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_tic_tac_toe', '0004_auto_20190712_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuttt',
            name='g0',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g1',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g2',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g3',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g4',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g5',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g6',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g7',
        ),
        migrations.RemoveField(
            model_name='gameuttt',
            name='g8',
        ),
    ]
