# Generated by Django 2.2.4 on 2019-08-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(default=1)),
                ('winner', models.IntegerField(default=0)),
                ('game_over', models.BooleanField(default=False)),
                ('p1', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='common_game_p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='common_game_p2', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_common.game_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DataCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('data', models.IntegerField(default=0)),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Game')),
            ],
        ),
    ]
