# Generated by Django 2.2.4 on 2019-08-20 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_pg_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=False, verbose_name='game over'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p1',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='common_game_p1', to=settings.AUTH_USER_MODEL, verbose_name='player 1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='common_game_p2', to=settings.AUTH_USER_MODEL, verbose_name='player 2'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.IntegerField(default=1, verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0, verbose_name='winner'),
        ),
    ]
