# Generated by Django 2.2.4 on 2019-08-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='full name'),
        ),
    ]
