# Generated by Django 2.2.4 on 2019-08-06 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
