# Generated by Django 2.2.4 on 2019-08-20 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190806_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='friends'),
        ),
        migrations.AlterField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='losses'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='wins'),
        ),
    ]
