# Generated by Django 2.2.4 on 2019-08-05 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='000000000', max_length=9)),
                ('player', models.IntegerField(default=1)),
                ('winner', models.IntegerField(default=0)),
                ('keep_score', models.BooleanField(default=True)),
                ('game_over', models.BooleanField(default=False)),
                ('play_id', models.IntegerField(default=0)),
                ('play_url', models.CharField(default='ttt:play', max_length=100)),
                ('p1', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttt_p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttt_p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('data', models.IntegerField(default=0)),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tic_tac_toe.GameTTT')),
            ],
        ),
    ]
