# Generated by Django 2.2.4 on 2019-08-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamettt',
            name='field',
        ),
    ]
