# Generated by Django 2.2.4 on 2019-08-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tic_tac_toe.gamettt',),
        ),
        migrations.CreateModel(
            name='MinimaxTTTAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tic_tac_toe.baseai',),
        ),
        migrations.CreateModel(
            name='RandomTTTAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tic_tac_toe.baseai',),
        ),
    ]
