# Generated by Django 2.2.4 on 2019-08-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0002_baseai_minimaxtttai_randomtttai'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegamaxTTTAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tic_tac_toe.baseai',),
        ),
    ]
