# Generated by Django 2.2.3 on 2019-07-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='field',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
