# Generated by Django 2.2.3 on 2019-07-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0002_auto_20190708_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='p1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p1', to='tic_tac_toe.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='p2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p2', to='tic_tac_toe.Player'),
        ),
    ]
