# Generated by Django 2.2.3 on 2019-07-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0003_auto_20190708_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='p1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttt_p1', to='tic_tac_toe.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttt_p2', to='tic_tac_toe.Player'),
        ),
    ]
