# Generated by Django 2.2.3 on 2019-07-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0005_remove_player_ties'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='keep_score',
            field=models.BooleanField(default=True),
        ),
    ]
