# Generated by Django 2.2.3 on 2019-07-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0009_auto_20190710_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('data', models.IntegerField(default=0)),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tic_tac_toe.GameTTT')),
            ],
        ),
    ]
