# Generated by Django 2.2.3 on 2019-07-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0010_datacell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamettt',
            name='p1',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttt_p1', to='tic_tac_toe.Player'),
        ),
        migrations.AlterField(
            model_name='gamettt',
            name='p2',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttt_p2', to='tic_tac_toe.Player'),
        ),
    ]
