# Generated by Django 2.2.4 on 2019-08-05 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUTTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_i', models.IntegerField(default=0)),
                ('prev_j', models.IntegerField(default=0)),
                ('player', models.IntegerField(default=1)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uttt_game', to='tic_tac_toe.GameTTT')),
                ('p1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uttt_p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uttt_p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameUTTT_ChildGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uttt_child_game', to='tic_tac_toe.GameTTT')),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_tic_tac_toe.GameUTTT')),
            ],
        ),
    ]
