# Generated by Django 2.2.4 on 2019-08-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ultimate_tic_tac_toe.gameuttt',),
        ),
        migrations.CreateModel(
            name='RandomUTTTAI',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ultimate_tic_tac_toe.baseai',),
        ),
    ]
