# Generated by Django 2.2.4 on 2019-08-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_tic_tac_toe', '0002_baseai_randomutttai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuttt',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uttt_game', to='tic_tac_toe.GameTTT', verbose_name='uttt game'),
        ),
    ]
